### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Zorlin3321** [iXab3r/MicSwitch#77]
Can't attach the .7z archive, the program won't save the other files, so I manually copied and pasted the one w/ the most info, Stacktrace, let me know if I messed up anything else.

Crashes on start, tried reinstalling, I set Media Play/Pause as the mute/unmute button, crashed immediately. Can't get it to work again.

Exception: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully.
   at WindowsHook.WinApi.HookResult.PrepareHandle(IFluentLog log, WindowsHookType hookType, Int32 nativeThreadId, WindowsHookDelegate hookProcedure) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookResult.cs:line 158
   at WindowsHook.WinApi.HookResultWithCallback..ctor(WindowsHookType hookType, WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookResult.cs:line 28
   at WindowsHook.WinApi.HookHelper.SetHook(WindowsHookType hookType, WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookHelper.cs:line 43
   at WindowsHook.WinApi.HookHelper.HookGlobalKeyboard(WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookHelper.cs:line 37
   at WindowsHook.Implementation.BaseListener..ctor(Subscribe subscribe) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\BaseListener.cs:line 31
   at WindowsHook.Implementation.KeyListener..ctor(Subscribe subscribe) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\KeyListener.cs:line 15
   at WindowsHook.Implementation.GlobalKeyListener..ctor() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\GlobalKeyListener.cs:line 13
   at WindowsHook.Implementation.GlobalEventFacade.CreateKeyListener() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\GlobalEventFacade.cs:line 16
   at WindowsHook.Implementation.EventFacade.<.ctor>b__3_0() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\EventFacade.cs:line 31
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at WindowsHook.Implementation.EventFacade.add_KeyDown(KeyEventHandler value) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\EventFacade.cs:line 55
   at PoeShared.Native.KeyboardEventsSource.<>c__DisplayClass46_0.<InitializeKeyboardHook>b__0(KeyEventHandler h) in C:\BuildAgent\work\61454f6050c7a045\Sources\PoeShared.Native\Native\SafeKeyboardMouseEvents.cs:line 209
   at System.Reactive.Linq.ObservableImpl.ClassicEventProducer`2.AddHandler(TDelegate handler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEvent.cs:line 368
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.AddHandler(TDelegate onNext) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEvent.cs:line 333

Message:

The operation completed successfully.StackTrace:

   at WindowsHook.WinApi.HookResult.PrepareHandle(IFluentLog log, WindowsHookType hookType, Int32 nativeThreadId, WindowsHookDelegate hookProcedure) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookResult.cs:line 158
   at WindowsHook.WinApi.HookResultWithCallback..ctor(WindowsHookType hookType, WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookResult.cs:line 28
   at WindowsHook.WinApi.HookHelper.SetHook(WindowsHookType hookType, WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookHelper.cs:line 43
   at WindowsHook.WinApi.HookHelper.HookGlobalKeyboard(WinHookCallback callback) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\WinApi\HookHelper.cs:line 37
   at WindowsHook.Implementation.BaseListener..ctor(Subscribe subscribe) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\BaseListener.cs:line 31
   at WindowsHook.Implementation.KeyListener..ctor(Subscribe subscribe) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\KeyListener.cs:line 15
   at WindowsHook.Implementation.GlobalKeyListener..ctor() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\GlobalKeyListener.cs:line 13
   at WindowsHook.Implementation.GlobalEventFacade.CreateKeyListener() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\GlobalEventFacade.cs:line 16
   at WindowsHook.Implementation.EventFacade.<.ctor>b__3_0() in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\EventFacade.cs:line 31
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at WindowsHook.Implementation.EventFacade.add_KeyDown(KeyEventHandler value) in C:\BuildAgent\work\61454f6050c7a045\Sources\WindowsHook\Implementation\EventFacade.cs:line 55
   at PoeShared.Native.KeyboardEventsSource.<>c__DisplayClass46_0.<InitializeKeyboardHook>b__0(KeyEventHandler h) in C:\BuildAgent\work\61454f6050c7a045\Sources\PoeShared.Native\Native\SafeKeyboardMouseEvents.cs:line 209
   at System.Reactive.Linq.ObservableImpl.ClassicEventProducer`2.AddHandler(TDelegate handler) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEvent.cs:line 368
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.AddHandler(TDelegate onNext) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEvent.cs:line 333

**Comment by iXab3r** [comment]
Will do some investigation this weekend, probably related to media buttons being handled incorrectly by my hooking system

Thanks for reporting it

**Comment by Zorlin3321** [comment]
Thanks.

**Comment by iXab3r** [comment]
Should be fixed as of 250+
